import os
import json
import requests
from mcp.server.fastmcp import FastMCP

# ==============================================================================
# Configuration & Architecture Alignment
# ==============================================================================
# These paths align perfectly with the llm-wiki.py and AgenticAgile.py structure
BASE_DIR = "."
RAW_DIR = os.path.join(BASE_DIR, "raw")
WIKI_DIR = os.path.join(BASE_DIR, "wiki")
STATE_FILE = os.path.join(WIKI_DIR, "project_state.json")

# Define local endpoints based on your previous infrastructure
ORCHESTRATOR_URL = os.getenv("ORCHESTRATOR_URL", "http://localhost:8080/v1/chat/completions")

# Initialize the FastMCP Server
# This creates an MCP server that communicates over standard input/output (stdio)
mcp = FastMCP("LocalAgenticWorkspace")

# ==============================================================================
# MCP RESOURCES (Read-Only Data Access)
# Allows external clients to read your workspace's internal state
# ==============================================================================

@mcp.resource("workspace://agile/state")
def get_project_state() -> str:
    """Returns the current Agile project state and tracked tasks."""
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE, "r", encoding="utf-8") as f:
            return f.read()
    return json.dumps({"error": "State file not found. Is AgenticAgile.py running?"})

@mcp.resource("workspace://wiki/index")
def get_wiki_index() -> str:
    """Returns the master index of the local LLM Wiki."""
    index_path = os.path.join(WIKI_DIR, "index.md")
    if os.path.exists(index_path):
        with open(index_path, "r", encoding="utf-8") as f:
            return f.read()
    return "No wiki index found."

@mcp.resource("workspace://wiki/synthesis")
def get_daily_synthesis() -> str:
    """Returns the latest Daily Synthesis generated by the Agile Manager."""
    synthesis_path = os.path.join(WIKI_DIR, "DAILY_SYNTHESIS.md")
    if os.path.exists(synthesis_path):
        with open(synthesis_path, "r", encoding="utf-8") as f:
            return f.read()
    return "No daily synthesis found."

# ==============================================================================
# MCP TOOLS (Actionable Capabilities)
# Allows external clients to trigger actions within your local ecosystem
# ==============================================================================

@mcp.tool()
def ingest_raw_document(filename: str, content: str, doc_type: str = "articles") -> str:
    """
    Drops a raw document into the workspace for ingestion by the local pipelines.
    
    Args:
        filename: The name of the file (e.g., 'new_concept.txt')
        content: The raw text content to be saved.
        doc_type: Subdirectory in raw/ (e.g., 'articles', 'papers', 'slack_logs').
    """
    # Sanitize the filename to prevent directory traversal attacks
    safe_name = "".join(c for c in filename if c.isalnum() or c in "._- ")
    
    # Ensure the target subdirectory exists
    target_dir = os.path.join(RAW_DIR, doc_type)
    os.makedirs(target_dir, exist_ok=True)
    
    filepath = os.path.join(target_dir, safe_name)
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
        
    return f"Success: Queued '{safe_name}' in 'raw/{doc_type}'. The AgenticAgile or Wiki pipelines will process this shortly."

@mcp.tool()
def query_local_orchestrator(prompt: str) -> str:
    """
    Directly queries your local Orchestrator LLM bypassing external APIs.
    Use this to leverage the local intelligence grid for reasoning tasks.
    """
    headers = {"Content-Type": "application/json"}
    payload = {
        "messages": [
            {"role": "system", "content": "You are the local orchestrator node exposed via MCP."},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.4,
        "max_tokens": 1024
    }
    
    try:
        response = requests.post(ORCHESTRATOR_URL, headers=headers, json=payload, timeout=60)
        response.raise_for_status()
        return response.json()['choices'][0]['message']['content']
    except requests.exceptions.ConnectionError:
        return "Error: Local Orchestrator is offline. Check if llama-server is running on port 8080."
    except Exception as e:
        return f"Inference Error: {str(e)}"

# ==============================================================================
# Execution
# ==============================================================================
if __name__ == "__main__":
    # MCP communicates over stdio by default, allowing it to be securely 
    # attached to local clients without opening network ports.
    mcp.run(transport="stdio")
