import os
import re
import datetime
from pathlib import Path
from openai import OpenAI

# Initialize client to hit your existing local llama-server
client = OpenAI(
    base_url=os.getenv("OPENAI_API_BASE", "http://localhost:8080/v1"),
    api_key=os.getenv("OPENAI_API_KEY", "sk-local")
)

# 1. Setup Directories based on the Idea File Architecture
BASE_DIR = Path(".")
RAW_DIR = BASE_DIR / "raw"
WIKI_DIR = BASE_DIR / "wiki"

# Immutable source layer subdirectories
for sub in ["articles", "papers", "repos", "assets"]:
    (RAW_DIR / sub).mkdir(parents=True, exist_ok=True)

# Mutable wiki layer subdirectories
for sub in ["concepts", "entities", "sources", "comparisons"]:
    (WIKI_DIR / sub).mkdir(parents=True, exist_ok=True)

# Core operational files
INDEX_FILE = WIKI_DIR / "index.md"
LOG_FILE = WIKI_DIR / "log.md"
OVERVIEW_FILE = WIKI_DIR / "overview.md"

for file in [INDEX_FILE, LOG_FILE, OVERVIEW_FILE]:
    if not file.exists():
        file.touch()

# 2. Schema / System Prompt matching the Idea File
SCHEMA_INSTRUCTIONS = """You are an automated knowledge compiler for an LLM Wiki.
Your job is to read raw source text and synthesize it into a structured Markdown wiki page.
Output ONLY the raw markdown with YAML frontmatter. Do not include conversational filler or explanations of what you are doing.

Every wiki page MUST have YAML frontmatter exactly matching this format:
---
title: [A concise, descriptive title]
type: [Must be exactly one of: concept, entity, source-summary, comparison]
sources: [[The filename of the source provided]]
related: [[List of potential related wiki pages]]
created: [Today's Date]
updated: [Today's Date]
confidence: [high, medium, or low]
---

Following the frontmatter, write the markdown content. Use well-structured headings, bullet points, and clear paragraphs to summarize the insights, contradictions, and key concepts from the source. Make it highly readable as a standalone wiki page.
"""

def log_ingest(filename: str, title: str, doc_type: str):
    """Appends an operational log of the ingestion event."""
    date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(f"- **{date_str}**: Ingested `{filename}` -> Created [{title}] (Type: {doc_type})\n")

def update_index(title: str, rel_path: str):
    """Appends the new page to the master index."""
    with open(INDEX_FILE, "a", encoding="utf-8") as f:
        f.write(f"- [{title}]({rel_path})\n")

def compile_document(source_path: Path):
    print(f"Ingesting {source_path.name}...")
    
    with open(source_path, "r", encoding="utf-8") as f:
        content = f.read()

    today = datetime.datetime.now().strftime("%Y-%m-%d")
    prompt = f"Compile the following raw document into a structured wiki page. Today's date is {today}. Source filename: {source_path.name}\n\n{content}"
    
    try:
        response = client.chat.completions.create(
            # Change "local-model" to the alias used by your llama-server instance if different
            model="local-model", 
            messages=[
                {"role": "system", "content": SCHEMA_INSTRUCTIONS},
                {"role": "user", "content": prompt}
            ],
            temperature=0.1,
            max_tokens=2048
        )
        
        wiki_content = response.choices[0].message.content.strip()
        
        # Strip markdown wrappers if the LLM hallucinated them
        if wiki_content.startswith("```markdown"):
            wiki_content = wiki_content[11:]
        if wiki_content.endswith("```"):
            wiki_content = wiki_content[:-3]
        wiki_content = wiki_content.strip()
            
        # Parse frontmatter to dynamically determine type and title
        doc_type = "sources" # default fallback
        title = source_path.stem
        
        # Made regex more forgiving for leading spaces/newlines generated by the LLM
        frontmatter_match = re.search(r"---\n(.*?)\n---", wiki_content, re.DOTALL)
        if frontmatter_match:
            fm = frontmatter_match.group(1)
            type_match = re.search(r"^type:\s*(.+)$", fm, re.MULTILINE)
            title_match = re.search(r"^title:\s*(.+)$", fm, re.MULTILINE)
            
            if type_match:
                parsed_type = type_match.group(1).strip().lower()
                # Route the file to the correct directory based on the parsed type
                if "concept" in parsed_type: doc_type = "concepts"
                elif "entity" in parsed_type: doc_type = "entities"
                elif "comparison" in parsed_type: doc_type = "comparisons"
                else: doc_type = "sources"
                
            if title_match:
                # Strip surrounding quotes if the LLM added them
                title = title_match.group(1).strip().replace('"', '').replace("'", "")
        
        # Format the final markdown filename safely
        safe_title = re.sub(r'[^a-zA-Z0-9\-_]', '-', title.lower())
        output_filename = f"{safe_title}.md"
        output_path = WIKI_DIR / doc_type / output_filename
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(wiki_content)
            
        print(f"Successfully compiled to {output_path}")
        
        # Execute secondary operations: Logging and Indexing
        rel_path = f"{doc_type}/{output_filename}"
        log_ingest(source_path.name, title, doc_type)
        update_index(title, rel_path)
        
    except Exception as e:
        print(f"Error compiling {source_path.name}: {e}")

def main():
    print("Starting LLM Wiki Ingestion Pipeline...")
    
    # Gather all readable raw files from the source subdirectories
    raw_files = []
    for ext in ["*.txt", "*.md", "*.csv"]:
        raw_files.extend(RAW_DIR.rglob(ext))
        
    if not raw_files:
        print(f"No source files found. Drop documents into 'raw/articles' or 'raw/papers' and run again.")
        return

    # Sequentially process all found files
    for file_path in raw_files:
        compile_document(file_path)
        
    print("Ingestion complete. Open the 'wiki/' folder in an editor like Obsidian to view.")

if __name__ == "__main__":
    main()
