import os
import json
import requests
from mcp.server.fastmcp import FastMCP
from requests.auth import HTTPBasicAuth

# ==============================================================================
# Configuration & Credentials
# ==============================================================================
ATLASSIAN_DOMAIN = os.getenv("ATLASSIAN_DOMAIN", "your-domain.atlassian.net")
ATLASSIAN_EMAIL = os.getenv("ATLASSIAN_EMAIL", "agent@yourdomain.com")
ATLASSIAN_API_TOKEN = os.getenv("ATLASSIAN_API_TOKEN", "your_api_token")
JIRA_PROJECT_KEY = os.getenv("JIRA_PROJECT_KEY", "AGILE")

JIRA_BASE_URL = f"https://{ATLASSIAN_DOMAIN}/rest/api/3"
CONFLUENCE_BASE_URL = f"https://{ATLASSIAN_DOMAIN}/wiki/rest/api"

# Standard paths aligning with your workspace
BASE_DIR = "."
WIKI_DIR = os.path.join(BASE_DIR, "wiki")
STATE_FILE = os.path.join(WIKI_DIR, "project_state.json")
SYNTHESIS_FILE = os.path.join(WIKI_DIR, "DAILY_SYNTHESIS.md")

auth = HTTPBasicAuth(ATLASSIAN_EMAIL, ATLASSIAN_API_TOKEN)
headers = {
    "Accept": "application/json",
    "Content-Type": "application/json"
}

# Initialize the FastMCP Server for Atlassian
mcp = FastMCP("AtlassianIngress")

# ==============================================================================
# MCP RESOURCES (Read-Only Context)
# ==============================================================================

@mcp.resource("atlassian://jira/active-sprint")
def get_active_sprint_issues() -> str:
    """Fetches all incomplete issues from the current Jira project."""
    jql = f"project = {JIRA_PROJECT_KEY} AND statusCategory != Done"
    url = f"{JIRA_BASE_URL}/search"
    
    try:
        response = requests.get(url, headers=headers, auth=auth, params={"jql": jql, "maxResults": 50})
        response.raise_for_status()
        issues = response.json().get("issues", [])
        
        simplified_issues = [
            {
                "key": issue["key"],
                "summary": issue["fields"]["summary"],
                "status": issue["fields"]["status"]["name"]
            } for issue in issues
        ]
        return json.dumps(simplified_issues, indent=2)
    except Exception as e:
        return json.dumps({"error": f"Failed to fetch Jira sprint: {str(e)}"})

# ==============================================================================
# MCP TOOLS (Agentic Actions)
# ==============================================================================

@mcp.tool()
def sync_local_tasks_to_jira() -> str:
    """
    Reads project_state.json from AgenticAgile.py and creates Jira tickets 
    for newly identified active tasks that don't have a Jira ticket yet.
    """
    if not os.path.exists(STATE_FILE):
        return "Error: project_state.json not found."
        
    with open(STATE_FILE, "r") as f:
        state = json.load(f)
        
    created_tickets = []
    
    for slug, task in state.get("tasks", {}).items():
        # Only push tasks that are active and don't already have an external tracker ID
        if task.get("status") == "active" and "jira_key" not in task:
            payload = json.dumps({
                "fields": {
                    "project": {"key": JIRA_PROJECT_KEY},
                    "summary": f"[{slug}] {task.get('content', 'Autogenerated Task')[:200]}",
                    "description": {
                        "type": "doc",
                        "version": 1,
                        "content": [{
                            "type": "paragraph",
                            "content": [{"text": f"Source: {task.get('source', 'Unknown')}\nConfidence: {task.get('confidence', 0)}", "type": "text"}]
                        }]
                    },
                    "issuetype": {"name": "Task"}
                }
            })
            
            try:
                response = requests.post(f"{JIRA_BASE_URL}/issue", data=payload, headers=headers, auth=auth)
                if response.status_code == 201:
                    issue_key = response.json().get("key")
                    task["jira_key"] = issue_key  # Update local state
                    created_tickets.append(issue_key)
            except Exception as e:
                print(f"Failed to create ticket for {slug}: {e}")
                
    # Save the updated state with the new Jira Keys
    if created_tickets:
        with open(STATE_FILE, "w") as f:
            json.dump(state, f, indent=4)
            
    return f"Successfully created {len(created_tickets)} Jira tickets: {', '.join(created_tickets)}"

@mcp.tool()
def publish_synthesis_to_confluence(page_id: str) -> str:
    """
    Reads the DAILY_SYNTHESIS.md generated by AgenticAgile.py and 
    publishes it to a specific Confluence page.
    """
    if not os.path.exists(SYNTHESIS_FILE):
        return "Error: DAILY_SYNTHESIS.md not found. Has AgenticAgile run?"
        
    with open(SYNTHESIS_FILE, "r") as f:
        markdown_content = f.read()
        
    # Note: Confluence APIs require storage format (XHTML), so we wrap the markdown in a macro 
    # or rely on a markdown-to-html converter. For simplicity, wrapping in preformatted text block.
    html_content = f"<ac:structured-macro ac:name='markdown'><ac:plain-text-body><![CDATA[{markdown_content}]]></ac:plain-text-body></ac:structured-macro>"
    
    # Get current page version to increment it
    try:
        get_resp = requests.get(f"{CONFLUENCE_BASE_URL}/content/{page_id}", headers=headers, auth=auth)
        get_resp.raise_for_status()
        current_version = get_resp.json()["version"]["number"]
        page_title = get_resp.json()["title"]
        
        payload = json.dumps({
            "version": {"number": current_version + 1},
            "title": page_title,
            "type": "page",
            "body": {
                "storage": {
                    "value": html_content,
                    "representation": "storage"
                }
            }
        })
        
        put_resp = requests.put(f"{CONFLUENCE_BASE_URL}/content/{page_id}", data=payload, headers=headers, auth=auth)
        put_resp.raise_for_status()
        
        return f"Successfully updated Confluence page '{page_title}' (ID: {page_id}) to version {current_version + 1}."
    except Exception as e:
        return f"Failed to publish to Confluence: {str(e)}"

# ==============================================================================
# Execution
# ==============================================================================
if __name__ == "__main__":
    print("Starting Atlassian Ingress MCP Server...")
    mcp.run(transport="stdio")
